kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: admin-teamcity-sa
  namespace: teamcity-server
subjects:
  - kind: ServiceAccount
    name: teamcity-sa
    namespace: teamcity-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin