kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openshift-teamcity-agent-custom
  namespace: teamcity-server
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'openshift-teamcity-agent-custom:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'docker.io/jetbrains/teamcity-agent:2021.2.3-linux-sudo'
      volumes:
        - name: ca-configmap
          source:
            type: ConfigMap
            configMap: 
              name: ca-configmap
              defaultMode: 420
              items:
                - key: service-ca.crt
                  path: service-ca.crt
          mounts: 
            - destinationPath: "/tmp/openshift"
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: >-
      FROM docker.io/jetbrains/teamcity-agent:2021.2.3-linux-sudo

      USER root

      WORKDIR /

      RUN curl -o oc.tar -L -O https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.8.0/openshift-client-linux.tar.gz \
          && tar -xvf oc.tar \
          && mv ./oc /usr/local/bin \
          && chmod ugo+x /usr/local/bin/oc \
          && oc version \
          && rm oc.tar \
          && cp /tmp/openshift/service-ca.crt /usr/local/share/ca-certificates \
          && keytool -storepass changeit -noprompt -trustcacerts -importcert -file /tmp/openshift/service-ca.crt -keystore /opt/java/openjdk/lib/security/cacerts \
          && update-ca-certificates \
          && chown -R 1000:1000 /services

      #Expose Ports
      EXPOSE 9090/tcp

      #Set User to buildagent
      USER 1000

    contextDir: /
  triggers:
    - type: ConfigChange
  runPolicy: Serial