kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: openshift-teamcity-testflask
  namespace: teamcity-server
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/teamcity-server/openshift-teamcity-testflask
