kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: openshift-teamcity-agent-custom
  namespace: teamcity-server
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/teamcity-server/openshift-teamcity-agent-custom
