apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/tidb-operator.openshift-operators: ''
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: tidb-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: tidb-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace


