kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: teamcity-data-pvc
  namespace: teamcity-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem

