apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-teamcity-example-tidb
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployables/TiDB/base
    repoURL: https://github.com/MoOyeg/openshift-teamcity-example.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: operators.coreos.com/v1alpha1
    kind: Subscription
    name: tidb-operator
    namespace: teamcity-server
    jsonPointers:
    - /status/conditions
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""