apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent-instance
  namespace: teamcity-server
spec:
  selector:
    matchLabels:
      app: teamcity-agent-instance
  replicas: 0
  template:
    metadata:
      labels:
        app: teamcity-agent-instance
    spec:
      containers:
        - name: teamcity-instance
          securityContext:
            #Running as privileged an root for Docker in Docker, Please note this is not secure.
            runAsUser: 0
            privileged: true
          resources:
            requests:
              memory: "1024Mi"
              cpu: "750m"
            limits:
              memory: "2048Mi"
              cpu: "1"   
          image: >-
            docker.io/jetbrains/teamcity-agent:2021.2.3-linux-sudo         
          ports:
            - containerPort: 9090
          env:
            - name: DOCKER_IN_DOCKER
              value: start
        #Diabling using the in-built Docker Agent via DOCKER_IN_DOCKER
        # - image: docker:20.10-dind
        #   name: docker
        #   securityContext:
        #     privileged: true
        #   volumeMounts:
        #     - mountPath: /var/lib/docker
        #       name: dind-storage
        #     - mountPath: /var/run/
        #       name: dind-socket
      volumes:
        - name: dind-storage
          emptyDir: {}
        - name: dind-socket
          emptyDir: {}
